create extension if not exists "pgcrypto";

-- Esta ampliacion convive con appointments y contacts para no interrumpir
-- la pagina ni el panel actuales durante la migracion historica.

create table if not exists public.branches (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  calendar_email text,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.branches (code, name, calendar_email, is_active)
values
  ('SN', 'San Nicolás', 'ms.suc.puentes@gmail.com', true),
  ('GPE_CENTRO', 'Guadalupe Centro', null, false),
  ('GPE_LINDAVISTA', 'Guadalupe Lindavista', null, false),
  ('MTY_SUR', 'Monterrey Poniente', 'ms.suc.mty@gmail.com', true),
  ('ESCOBEDO', 'Escobedo', 'ms.suc.escobedo@gmail.com', false)
on conflict (code) do update set
  name = excluded.name,
  calendar_email = coalesce(excluded.calendar_email, public.branches.calendar_email),
  is_active = excluded.is_active,
  updated_at = now();

create table if not exists public.nutritionists (
  id smallint generated by default as identity primary key,
  branch_id smallint references public.branches(id) on delete set null,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (branch_id, name)
);

create table if not exists public.services_catalog (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  is_active boolean not null default true
);

insert into public.services_catalog (code, name, is_active)
values ('sesion_integral_399', 'Sesión integral $399', true)
on conflict (code) do update set
  name = excluded.name,
  is_active = excluded.is_active;

create table if not exists public.patient_profiles (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  name_key text generated always as (
    lower(regexp_replace(btrim(full_name), '\s+', ' ', 'g'))
  ) stored,
  whatsapp text,
  whatsapp_status smallint not null default 0 check (whatsapp_status in (0, 1)),
  promotional_consent smallint not null default 1 check (promotional_consent in (-1, 0, 1)),
  source_patient_key text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (whatsapp_status = 0 and whatsapp is null)
    or
    (whatsapp_status = 1 and whatsapp ~ '^\+[1-9][0-9]{7,14}$')
  )
);

-- WhatsApp no es unico: familiares distintos pueden compartir el mismo numero.
create index if not exists patient_profiles_whatsapp_idx
on public.patient_profiles (whatsapp)
where whatsapp is not null;

create index if not exists patient_profiles_name_key_idx
on public.patient_profiles (name_key);

create table if not exists public.patient_appointment_history (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.patient_profiles(id) on delete cascade,
  branch_id smallint not null references public.branches(id),
  nutritionist_id smallint references public.nutritionists(id) on delete set null,
  service_id smallint references public.services_catalog(id) on delete set null,
  scheduled_at timestamptz not null,
  original_scheduled_at timestamptz,
  sequence_number smallint check (sequence_number is null or sequence_number > 0),
  confirmed boolean,
  attended boolean,
  released_at_8 boolean not null default false,
  cancelled boolean not null default false,
  source_kind smallint not null check (source_kind in (1, 2, 3, 4)),
  source_event_key text unique,
  calendar_event_id text,
  legacy_appointment_id uuid unique references public.appointments(id) on delete set null,
  confidence smallint not null default 100 check (confidence between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (not (attended is true and (released_at_8 or cancelled)))
);

create index if not exists patient_history_calendar_event_idx
on public.patient_appointment_history (branch_id, calendar_event_id)
where calendar_event_id is not null;

create index if not exists patient_history_patient_date_idx
on public.patient_appointment_history (patient_id, scheduled_at desc);

create index if not exists patient_history_branch_date_idx
on public.patient_appointment_history (branch_id, scheduled_at desc);

create index if not exists patient_history_retargeting_idx
on public.patient_appointment_history (branch_id, attended, confirmed, released_at_8, scheduled_at desc);

create table if not exists public.calendar_sync_sources (
  id smallint generated by default as identity primary key,
  branch_id smallint not null unique references public.branches(id) on delete cascade,
  calendar_id text not null unique,
  is_enabled boolean not null default false,
  sync_token text,
  last_sync_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.calendar_sync_sources (branch_id, calendar_id, is_enabled)
select id, calendar_email, false
from public.branches
where code in ('SN', 'MTY_SUR') and calendar_email is not null
on conflict (branch_id) do update set
  calendar_id = excluded.calendar_id,
  updated_at = now();

-- Solo conserva una huella protegida del telefono, nunca el nombre ni notas.
create table if not exists public.contact_suppressions (
  contact_fingerprint text primary key,
  reason_code smallint not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.retargeting_campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  branch_id smallint references public.branches(id) on delete set null,
  segment_key text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.retargeting_messages (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.retargeting_campaigns(id) on delete cascade,
  patient_id uuid not null references public.patient_profiles(id) on delete cascade,
  delivery_status smallint not null default 0,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (campaign_id, patient_id)
);

create index if not exists retargeting_messages_patient_date_idx
on public.retargeting_messages (patient_id, sent_at desc);

create or replace view public.patient_branch_activity
with (security_invoker = true)
as
select
  h.patient_id,
  h.branch_id,
  min(coalesce(h.original_scheduled_at, h.scheduled_at)) as first_appointment_at,
  max(coalesce(h.original_scheduled_at, h.scheduled_at)) as last_appointment_at,
  max(coalesce(h.original_scheduled_at, h.scheduled_at)) filter (where h.attended is true) as last_attended_at,
  count(*)::integer as total_appointments,
  count(*) filter (where h.attended is true)::integer as attended_appointments,
  count(*) filter (
    where h.confirmed is true
      and h.attended is not true
      and coalesce(h.original_scheduled_at, h.scheduled_at) < now()
  )::integer as confirmed_without_attendance,
  count(*) filter (where h.released_at_8)::integer as released_appointments,
  bool_or(
    coalesce(h.original_scheduled_at, h.scheduled_at) >= now()
    and not h.released_at_8
    and not h.cancelled
    and h.attended is not true
  ) as has_future_appointment
from public.patient_appointment_history h
group by h.patient_id, h.branch_id;

create or replace view public.patient_activity_summary
with (security_invoker = true)
as
with activity as (
  select
    p.id as patient_id,
    p.full_name,
    p.whatsapp,
    p.whatsapp_status,
    p.promotional_consent,
    min(coalesce(h.original_scheduled_at, h.scheduled_at)) as first_appointment_at,
    max(coalesce(h.original_scheduled_at, h.scheduled_at)) as last_appointment_at,
    max(coalesce(h.original_scheduled_at, h.scheduled_at)) filter (where h.attended is true) as last_attended_at,
    count(h.id)::integer as total_appointments,
    count(h.id) filter (where h.attended is true)::integer as attended_appointments,
    count(h.id) filter (
      where h.confirmed is true
        and h.attended is not true
        and coalesce(h.original_scheduled_at, h.scheduled_at) < now()
    )::integer as confirmed_without_attendance,
    count(h.id) filter (where h.released_at_8)::integer as released_appointments,
    bool_or(
      coalesce(h.original_scheduled_at, h.scheduled_at) >= now()
      and not h.released_at_8
      and not h.cancelled
      and h.attended is not true
    ) as has_future_appointment
  from public.patient_profiles p
  left join public.patient_appointment_history h on h.patient_id = p.id
  group by p.id, p.full_name, p.whatsapp, p.whatsapp_status, p.promotional_consent
), last_branch as (
  select distinct on (h.patient_id)
    h.patient_id,
    h.branch_id as last_branch_id
  from public.patient_appointment_history h
  order by h.patient_id, coalesce(h.original_scheduled_at, h.scheduled_at) desc, h.created_at desc
)
select
  a.*,
  lb.last_branch_id,
  case
    when coalesce(a.has_future_appointment, false) then 'con_cita_futura'
    when a.attended_appointments = 0 and a.confirmed_without_attendance > 0 then 'agendo_no_acudio'
    when a.attended_appointments = 0 then 'sin_asistencia_comprobada'
    when a.attended_appointments = 1 then 'primera_consulta_sin_regreso'
    when a.last_attended_at >= now() - interval '30 days' then 'activa'
    when a.last_attended_at >= now() - interval '60 days' then 'seguimiento'
    when a.last_attended_at >= now() - interval '120 days' then 'inactiva'
    else 'reactivacion'
  end as segment_key,
  (
    a.whatsapp_status = 1
    and a.promotional_consent = 1
    and not coalesce(a.has_future_appointment, false)
  ) as promotion_ready
from activity a
left join last_branch lb on lb.patient_id = a.patient_id;

create or replace function public.sync_operational_appointment_to_history(p_appointment_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  a public.appointments%rowtype;
  patient_uuid uuid;
  branch_smallint smallint;
  service_smallint smallint;
  combined_name text;
  combined_name_key text;
  appointment_timestamp timestamptz;
begin
  select * into a from public.appointments where id = p_appointment_id;
  if not found then return; end if;

  combined_name := regexp_replace(btrim(concat_ws(' ', a.first_name, a.last_name)), '\s+', ' ', 'g');
  combined_name_key := lower(combined_name);

  select id into branch_smallint from public.branches where code = 'SN';

  select p.id into patient_uuid
  from public.patient_profiles p
  where p.whatsapp = a.whatsapp
    and p.name_key = combined_name_key
  order by p.created_at
  limit 1;

  if patient_uuid is null then
    insert into public.patient_profiles (
      full_name,
      whatsapp,
      whatsapp_status,
      promotional_consent
    ) values (
      combined_name,
      case when a.whatsapp ~ '^\+[1-9][0-9]{7,14}$' then a.whatsapp else null end,
      case when a.whatsapp ~ '^\+[1-9][0-9]{7,14}$' then 1 else 0 end,
      1
    ) returning id into patient_uuid;
  end if;

  select id into service_smallint
  from public.services_catalog
  where code = coalesce(a.service, 'sesion_integral_399')
  limit 1;

  appointment_timestamp := (a.appointment_date + a.appointment_time) at time zone 'America/Monterrey';

  insert into public.patient_appointment_history (
    patient_id,
    branch_id,
    service_id,
    scheduled_at,
    confirmed,
    attended,
    released_at_8,
    cancelled,
    source_kind,
    source_event_key,
    calendar_event_id,
    legacy_appointment_id,
    confidence,
    updated_at
  ) values (
    patient_uuid,
    branch_smallint,
    service_smallint,
    appointment_timestamp,
    case when a.status in ('confirmed', 'completed') then true else null end,
    case when a.status = 'completed' then true else null end,
    a.appointment_time = time '08:00',
    a.status = 'cancelled',
    case when a.origin = 'yosoysano' then 4 else 1 end,
    'current:' || a.id::text,
    a.google_calendar_event_id,
    a.id,
    100,
    now()
  )
  on conflict (legacy_appointment_id) do update set
    patient_id = excluded.patient_id,
    branch_id = excluded.branch_id,
    service_id = excluded.service_id,
    scheduled_at = excluded.scheduled_at,
    confirmed = excluded.confirmed,
    attended = excluded.attended,
    released_at_8 = excluded.released_at_8,
    cancelled = excluded.cancelled,
    calendar_event_id = excluded.calendar_event_id,
    updated_at = now();
end;
$$;

create or replace function public.mirror_operational_appointment_to_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  begin
    perform public.sync_operational_appointment_to_history(new.id);
  exception when others then
    raise warning 'No se pudo reflejar la cita % en el historial: %', new.id, sqlerrm;
  end;
  return new;
end;
$$;

drop trigger if exists mirror_operational_appointment_history on public.appointments;
create trigger mirror_operational_appointment_history
after insert or update of first_name, last_name, whatsapp, appointment_date, appointment_time, status, google_calendar_event_id, service
on public.appointments
for each row execute function public.mirror_operational_appointment_to_history();

-- Integra las citas que ya existen sin alterar appointments ni contacts.
do $$
declare existing_appointment record;
begin
  for existing_appointment in select id from public.appointments loop
    perform public.sync_operational_appointment_to_history(existing_appointment.id);
  end loop;
end;
$$;

alter table public.branches enable row level security;
alter table public.nutritionists enable row level security;
alter table public.services_catalog enable row level security;
alter table public.patient_profiles enable row level security;
alter table public.patient_appointment_history enable row level security;
alter table public.calendar_sync_sources enable row level security;
alter table public.contact_suppressions enable row level security;
alter table public.retargeting_campaigns enable row level security;
alter table public.retargeting_messages enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'branches',
    'nutritionists',
    'services_catalog',
    'patient_profiles',
    'patient_appointment_history',
    'calendar_sync_sources',
    'contact_suppressions',
    'retargeting_campaigns',
    'retargeting_messages'
  ] loop
    execute format('drop policy if exists "Admins manage %1$s" on public.%1$I', table_name);
    execute format(
      'create policy "Admins manage %1$s" on public.%1$I for all using (exists (select 1 from public.admin_users where admin_users.email = auth.jwt() ->> ''email'')) with check (exists (select 1 from public.admin_users where admin_users.email = auth.jwt() ->> ''email''))',
      table_name
    );
  end loop;
end;
$$;

grant select on public.branches, public.nutritionists, public.services_catalog to authenticated;
grant select, insert, update, delete on public.patient_profiles, public.patient_appointment_history to authenticated;
grant select on public.patient_branch_activity, public.patient_activity_summary to authenticated;
grant all on public.branches, public.nutritionists, public.services_catalog to service_role;
grant all on public.patient_profiles, public.patient_appointment_history to service_role;
grant all on public.calendar_sync_sources, public.contact_suppressions to service_role;
grant all on public.retargeting_campaigns, public.retargeting_messages to service_role;
grant select on public.patient_branch_activity, public.patient_activity_summary to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on public.calendar_sync_sources from anon, authenticated;
revoke all on public.contact_suppressions from anon, authenticated;
revoke all on public.retargeting_campaigns from anon;
revoke all on public.retargeting_messages from anon;

select pg_notify('pgrst', 'reload schema');
