-- Información pública y vigencias de las dos sucursales activas.
-- Las ubicaciones se conservan por periodo para no perder el historial.

alter table public.branches
  add column if not exists public_name text,
  add column if not exists whatsapp text,
  add column if not exists whatsapp_url text,
  add column if not exists website_url text,
  add column if not exists booking_url text,
  add column if not exists facebook_url text,
  add column if not exists appointment_only boolean not null default true,
  add column if not exists payment_methods text[] not null default array[]::text[],
  add column if not exists has_parking boolean not null default false,
  add column if not exists wheelchair_accessible boolean not null default false,
  add column if not exists has_restroom boolean not null default false;

update public.branches
set
  name = case code
    when 'SN' then 'Más Sano Nutrición Holística - Suc. San Nicolás'
    when 'MTY_SUR' then 'Más Sano Nutrición Holística - Suc. Monterrey Poniente'
    else name
  end,
  public_name = case code
    when 'SN' then 'Más Sano Nutrición Holística - Suc. San Nicolás'
    when 'MTY_SUR' then 'Más Sano Nutrición Holística - Suc. Monterrey Poniente'
    else public_name
  end,
  whatsapp = '+528186935634',
  whatsapp_url = 'https://wa.me/528186935634',
  website_url = 'https://massanonh.com/',
  booking_url = 'https://agenda.massanonh.com/',
  facebook_url = 'https://www.facebook.com/MasSanoNH',
  appointment_only = true,
  payment_methods = array['efectivo', 'transferencia', 'tarjeta_credito', 'tarjeta_debito'],
  has_parking = true,
  wheelchair_accessible = true,
  has_restroom = true,
  updated_at = now()
where code in ('SN', 'MTY_SUR');

create table if not exists public.branch_locations (
  id smallint generated by default as identity primary key,
  branch_id smallint not null references public.branches(id) on delete cascade,
  label text not null,
  address text not null,
  maps_url text not null,
  valid_from date not null,
  valid_until date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, valid_from),
  check (valid_until is null or valid_until >= valid_from)
);

insert into public.branch_locations (branch_id, label, address, maps_url, valid_from, valid_until)
select id, 'Las Puentes', 'Av. Las Puentes 511, Las Puentes 3er Sector, San Nicolás de los Garza, N.L.',
  'https://maps.app.goo.gl/CwQyKxpUpvgNCEjX7', date '2016-01-01', date '2026-08-01'
from public.branches where code = 'SN'
on conflict (branch_id, valid_from) do update set
  label = excluded.label, address = excluded.address, maps_url = excluded.maps_url,
  valid_until = excluded.valid_until, updated_at = now();

insert into public.branch_locations (branch_id, label, address, maps_url, valid_from, valid_until)
select id, 'Anáhuac', 'Col. Anáhuac, San Nicolás de los Garza, N.L.',
  'https://maps.app.goo.gl/T67AE5ndW6guX5sc8', date '2026-08-02', null
from public.branches where code = 'SN'
on conflict (branch_id, valid_from) do update set
  label = excluded.label, address = excluded.address, maps_url = excluded.maps_url,
  valid_until = excluded.valid_until, updated_at = now();

insert into public.branch_locations (branch_id, label, address, maps_url, valid_from, valid_until)
select id, 'Plaza Real · ALFAO Business Center', 'Plaza Real, Av. Dr. José Eleuterio González 315, SUB-4, Jardines del Cerro, Monterrey, N.L., C.P. 64050. Segundo piso, dentro de ALFAO Business Center.',
  'https://maps.app.goo.gl/HE2SPPVTPo27Zh2U6', date '2026-08-03', null
from public.branches where code = 'MTY_SUR'
on conflict (branch_id, valid_from) do update set
  label = excluded.label, address = excluded.address, maps_url = excluded.maps_url,
  valid_until = excluded.valid_until, updated_at = now();

alter table public.branch_locations enable row level security;

drop policy if exists "Admins manage branch_locations" on public.branch_locations;
create policy "Admins manage branch_locations"
on public.branch_locations
for all
using (exists (
  select 1 from public.admin_users where admin_users.email = auth.jwt() ->> 'email'
))
with check (exists (
  select 1 from public.admin_users where admin_users.email = auth.jwt() ->> 'email'
));

grant select on public.branch_locations to authenticated;
grant all on public.branch_locations to service_role;
grant usage, select on sequence public.branch_locations_id_seq to service_role;
revoke all on public.branch_locations from anon;

select pg_notify('pgrst', 'reload schema');
