-- Bandeja compacta de WhatsApp para el numero de campañas de Más Sano.
-- Una conversación pertenece a un numero de WhatsApp. Los pacientes familiares
-- que compartan ese numero continúan separados en patient_profiles.

create table if not exists public.whatsapp_conversations (
  id uuid primary key default gen_random_uuid(),
  whatsapp text not null unique check (whatsapp ~ '^\+[1-9][0-9]{7,14}$'),
  contact_name text,
  status smallint not null default 1 check (status in (0, 1)),
  unread_count integer not null default 0 check (unread_count >= 0),
  last_inbound_at timestamptz,
  last_message_at timestamptz,
  last_message_preview text,
  last_message_direction smallint check (last_message_direction in (1, 2)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists whatsapp_conversations_recent_idx
on public.whatsapp_conversations (last_message_at desc nulls last);

create table if not exists public.whatsapp_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.whatsapp_conversations(id) on delete cascade,
  meta_message_id text not null unique,
  direction smallint not null check (direction in (1, 2)),
  message_type text not null default 'text',
  body text,
  delivery_status smallint not null default 0 check (delivery_status in (-1, 0, 1, 2, 3)),
  sent_at timestamptz not null,
  delivered_at timestamptz,
  read_at timestamptz,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists whatsapp_messages_conversation_date_idx
on public.whatsapp_messages (conversation_id, sent_at desc);

alter table public.whatsapp_conversations enable row level security;
alter table public.whatsapp_messages enable row level security;

drop policy if exists "Admins manage whatsapp conversations" on public.whatsapp_conversations;
create policy "Admins manage whatsapp conversations"
on public.whatsapp_conversations
for all
using (exists (
  select 1 from public.admin_users
  where admin_users.email = auth.jwt() ->> 'email'
))
with check (exists (
  select 1 from public.admin_users
  where admin_users.email = auth.jwt() ->> 'email'
));

drop policy if exists "Admins manage whatsapp messages" on public.whatsapp_messages;
create policy "Admins manage whatsapp messages"
on public.whatsapp_messages
for all
using (exists (
  select 1 from public.admin_users
  where admin_users.email = auth.jwt() ->> 'email'
))
with check (exists (
  select 1 from public.admin_users
  where admin_users.email = auth.jwt() ->> 'email'
));

grant select, insert, update on public.whatsapp_conversations to authenticated, service_role;
grant select, insert, update on public.whatsapp_messages to authenticated, service_role;
grant usage, select on sequence public.whatsapp_messages_id_seq to authenticated, service_role;
revoke all on public.whatsapp_conversations from anon;
revoke all on public.whatsapp_messages from anon;

